openapi: 3.0.0
info:
  title: MetricsBuilder API
  description: MetricsBuilder APIs for Accessing Monitoring Metrics Collected via MonSter.
  contact:
    email: jie.li@ttu.edu
    name: Jie Li
  license: 
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
  
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local development server
    variables:
      port:
        default: '5001'
      basePath:
        default: v2
  - url: http://hugo.hpcc.ttu.edu:{port}/{basePath}
    description: Hugo Server
    variables:
      port:
        default: '5000'
      basePath:
        default: v2

paths:
  /metricsbuilder:      
    get:
      summary: Query Monitoring Metrics
      description: Execute queries for monitoring metrics, job information, etc.
      operationId: metricsbuilder
      parameters:
      - description: Start time of the time range
        in: query
        name: start
        schema:
          example: '2024-2-14T10:00:00-06:00'
          format: date-time
          type: string
      - description: End time of the time range
        in: query
        name: end
        schema:
          example: '2024-2-14T12:00:00-06:00'
          format: date-time
          type: string
      - description: Time interval for aggregating the metrics.
        in: query
        name: interval
        schema:
          type: string
          pattern: ^[1-9][0-9]*[s, m, h, d, w]$
          default: 5m
          example: 5m
      - description: Aggregation function.
        in: query
        name: aggregation
        required: false
        schema:
          type: string
          enum:
          - min
          - max
          - mean
          - median
          default: max
          example: max
      - description: Target nodes in the cluster.
        in: query
        name: nodelist
        required: false
        schema:
          type: string
          default: 10.101.1.[1-60],10.101.2.[1-60]
          example: 10.101.1.[1-60],10.101.7.[1-3,5-60]
      - description: Selected Metrics.
        explode: true
        in: query
        name: metrics
        required: false
        schema:
          items:
            enum:
            - SystemPower_iDRAC
            - CPUPower_iDRAC
            - MemoryPower_iDRAC
            - Fan_iDRAC
            - Temperature_iDRAC
            - MemoryUsage_Slurm
            - NodeJobsCorrelation_Slurm
            - JobsInfo_Slurm
            - NodesState_Slurm
            type: string
          type: array
          default:
          - SystemPower_iDRAC
          - NodeJobsCorrelation_Slurm
          - JobsInfo_Slurm
      - description: Return compressed data.
        in: query
        name: compression
        required: false
        schema:
          type: boolean
          enum:
          - true
          - false
          default: true
          example: true
      responses:
        "200":
          description: Return metrics for web applications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebResponse'
              example:
                jobs_info:
                  5000001:
                    name: test1
                    cpus: 72,
                    node_count: 2
                    batch_host: "cpu-1-1"
                    nodes: ["cpu-1-1","cpu-1-2"]
                    start_time: 1648956000
                    end_time: 1684956000
                    user_id: 100001
                    user_name: username1
                nodes_info:
                  cpu-1-1:
                    cpus: [ [18,2],[18,2] ]
                    jobs: [ [5688032,5689127],[5688032,5689127] ]
                    system_power: [264,300]
                time_stamp: [1651149550,1651149850]
        default:
            $ref: '#/components/responses/DefaultError'

  /queue:
    get:
      summary: Get Queue Status of Slurm
      operationId: queue
      responses:
        '200':
          description: Get qeueu status succesfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueueStatus'
              example:
                timestamp: 1651181880
                queue_status:
                - ACCOUNT: "default"
                - TRES_PER_NODE: "gpu:1"
                - MIN_CPUS: "1"
                - MIN_TMP_DISK: "0"
                - END_TIME: 1651206259
                - FEATURES: "(null)"
                - GROUP: "CS"
                - OVER_SUBSCRIBE: "OK"
                - JOBID: "5692509"
                - NAME: "models"
                - COMMENT: "(null)"
                - TIME_LIMIT: "10:00:00"
                - MIN_MEMORY: "9639M"
                - REQ_NODES: ""
                - COMMAND: "/home/user/project/code/job.sh"
                - PRIORITY: "0.00000131200068"
                - QOS: "normal"
                - REASON: "None"
                - ST: "R"
                - USER: "username1"
                - RESERVATION: "(null)"
                - WCKEY: "(null)"
                - EXC_NODES: ""
                - NICE: "0"
                - S:C:T: "*:*:*"
                - EXEC_HOST: "cpu-23-1"
                - CPUS: 1
                - NODES: "1"
                - DEPENDENCY: "(null)"
                - ARRAY_JOB_ID: "5692509"
                - SOCKETS_PER_NODE: "*"
                - CORES_PER_SOCKET: "*"
                - THREADS_PER_CORE: "*"
                - ARRAY_TASK_ID: "N/A"
                - TIME_LEFT: "6:46:19"
                - TIME: "3:13:41"
                - NODELIST: ["cpu-23-1"]
                - CONTIGUOUS: "0"
                - PARTITION: "nocona"
                - NODELIST(REASON): "cpu-23-1"
                - START_TIME: 1651170259
                - STATE: "RUNNING"
                - UID: "100011"
                - SUBMIT_TIME: 1651170257
                - LICENSES: "(null)"
                - CORE_SPEC: "N/A"
                - SCHEDNODES: "(null)"
                - WORK_DIR: "/home/user/project/code"
        default:
          $ref: '#/components/responses/DefaultError'

components:
  schemas:
    WebResponse: 
      properties:
        nodes_metrics:
          items:
            type: object
          type: array
        jobs_info:
          items:
            type: object
          type: array
        timestamps:
          items:
            type: integer
          type: array
    SlurmData:
      type: object
      properties:
        ACCOUNT: 
          type: string
        TRES_PER_NODE:
          type: string
        MIN_CPUS:
          type: string
        MIN_TMP_DISK:
          type: string
        END_TIME: 
          type: number
        FEATURES: 
          type: string
        GROUP:
          type: string
        OVER_SUBSCRIBE:
          type: string
        JOBID:
          type: string
        NAME:
          type: string
        COMMENT:
          type: string
        TIME_LIMIT:
          type: string
        MIN_MEMORY:
          type: string
        REQ_NODES:
          type: string
        COMMAND:
          type: string
        PRIORITY:
          type: string
        QOS:
          type: string
        REASON:
          type: string
        ST:
          type: string
        USER:
          type: string
        RESERVATION:
          type: string
        WCKEY:
          type: string
        EXC_NODES:
          type: string
        NICE:
          type: string
        S:C:T:
          type: string
        EXEC_HOST:
          type: string
        CPUS:
          type: number
        NODES:
          type: string
        DEPENDENCY:
          type: string
        ARRAY_JOB_ID:
          type: string
        SOCKETS_PER_NODE:
          type: string
        CORES_PER_SOCKET:
          type: string
        THREADS_PER_CORE:
          type: string
        ARRAY_TASK_ID:
          type: string
        TIME_LEFT:
          type: string
        TIME:
          type: string
        NODELIST: 
          type: array
          items: 
            type: string
        CONTIGUOUS:
          type: string
        PARTITION:
          type: string
        NODELIST(REASON):
          type: string
        START_TIME:
          type: number
        STATE:
          type: string
        UID: 
          type: string
        SUBMIT_TIME: 
          type: number
        LICENSES: 
          type: string
        CORE_SPEC:
          type: string
        SCHEDNODES:
          type: string
        WORK_DIR:
          type: string

    QueueStatus:
      properties:
        timestamps: 
          type: number
        queue_status:
          type: array
          items:
            $ref: '#/components/schemas/SlurmData'

  responses:
    DefaultError:
      description: default error
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              message:
                type: string
          example:
            name: 'ERROR'
            message: 'Internal Server Error'