influxdb:
  host: '10.10.1.3'
  port: '8086'
  user: 'root'
  password: '1234'
  database: 'test_monster'

frequency: 
  60

hostlistdir: './hostlist'

redfish:
  user: 'root'
  password: 'nivipnut'
  timeout: 
    connect: 4 # connect timeout
    read: 12   # read timeout
  max_retries: 3
  ssl_verify: False   # Secure Sockets Layer Verify
  hostlist: "./hostlist"

uge:
  host: '129.118.104.35'
  port: '8182'
  user: 'username'
  password: 'password'
  timeout: 
    connect: 2
    read: 6
  max_retries: 3
  ssl_verify: False