influxdb:
  host: 'localhost'
  port: '8086'
  user: 'root'
  password: '1234'
  database: 'hpcc_metrics'

frequency: 
  60

redfish:
  user: 'root'
  password: 'nivipnut'
  timeout: 
    connect: 5 # connect timeout
    read: 10   # read timeout
  max_retries: 3
  ssl_verify: False   # Secure Sockets Layer Verify

uge:
  host: '129.118.104.35'
  port: '8182'
  user: 'username'
  password: 'password'
  timeout: 
    connect: 2
    read: 6
  max_retries: 3
  ssl_verify: False