#----------------------------------BMC metrics----------------------------------
# Time should be in nanosecond or follow rfc3339
# Measurement of BMC metrics is followed by Redfish entry point name,
# e.g. CPU1_Temp is get from "/redfish/v1/Chassis/System.Embedded.1/Thermal",
# thus CPU1_Temp will be saved into measurement "Thermal". 
# Tag keys of BMC metrics are constrained to "Label" and "NodeId"; By indexing
# these two tags, we can get the only reading value, which is saved into field
# key "Reading"

# Dummy data points in "Thermal" measurement
measurement: Thermal         
time: 1583792296000000000
tags: 
    - Label: "CPU1Temp"
    - NodeId: "101.10.1.1"
fields:
    - Reading: 46.00

measurement: Thermal         
time: 1583792296000000000          
tags: 
    - Label: "FAN_1"
    - NodeId: "101.10.1.1"
fields:
    - Reading: 4500.00

# CPU2Temp, FAN2, FAN3, FAN4, InletTemp etc.

# Dummy data points in "Power" measurement
measurement: Power           
time: 1583792296000000000
tags: 
    - Label: "NodePower"
    - NodeId: "101.10.1.1"
fields:
    - Reading: 277.00
#------------------------------End BMC metrics----------------------------------

#----------------------------------UGE metrics----------------------------------
# Resource usage (CPU usage and Memory usage) related metrics from UGE are saved 
# into measurement "UGE"; Tag key and field key names follow the BMC metrics, 
# in which only "Label", "NodeId" and "Reading" are kept. 

# Dummy data points in "UGE" measurement
measurement: UGE            # UGE metrics
time: 1583792296000000000             
tags: 
    - Label: "CPUUsage"
    - NodeId: "101.10.1.1"
fields:
    - Reading: 0.50

measurement: UGE            
time: 1583792296000000000             
tags: 
    - Label: "MemUsage"
    - NodeId: "101.10.1.1"
fields:
    - Reading: 0.50

# Node-Jobs relationship is saved in "NodeJobs" measurement. Tag key is "NodeId",
# from which we can get the corresponding field value that is a list of job IDs.

# Dummy data points in "NodeJobs" measurement
measurement: NodeJobs
time: 1583792296000000000             
tags: 
    - NodeId: "101.10.1.1"
fields:
    - JobList: "['123456', '123457']"

# Job details are saved in "JobsInfo" measurement. Tag key is "JobId" and "Queue", 
# from which we can get the corresponding job details that are saved into field. The data 
# point in this measurement is inserted only when a new job is submitted.

# Dummy data points in "JobsInfo" measurement
measurement: JobsInfo
time: 1583792296000000000              
tags: 
    - JobId: '123456'
    - Queue: 'quanah'
fields:
    - StartTime: 1583792200   
    - SubmitTime: 1583792200  
    - TotalNodes: 2
    - NodeList: "['10.101.1.1', '10.101.1.2']"
    - CPUCores: 72
    - JobName: 'test'
    - User: "abc"
#------------------------------End UGE metrics----------------------------------