# MIT License
#
# Copyright (c) 2022 Texas Tech University
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# This file is part of MonSter.
#
# Author:
#     Jie Li, jie.li@ttu.edu


# TimeScaleDB Configuration
timescaledb: 
  host: 0.0.0.0
  port: 5432
  username: username
  password: password
  database: database

# iDRAC Configuration
idrac:
  username: username
  password: password
  nodelist:
    - 10.101.1.[1-60]
    - 10.101.2.[1-60]
    - 10.101.3.[1-60]
    - 10.101.4.[1-60]

# Slurm REST API Configuration
slurm_rest_api:
  ip: 10.100.1.1
  port: 6820
  user: username
  headnode: login.headnode
  slurm_jobs: /slurm/v0.0.36/jobs/
  slurm_nodes: /slurm/v0.0.36/nodes/
  openapi: /openapi/v3

# OS - iDRAC hostname mapping. Key is the hostname obtained from Slurm REST API(
# aligned with OS hostname), value is the hostname read from iDRAC interface. 
# Leave empty if OS hostname is already aligned with iDRAC hostname.
hostnames:
  # cpu-23-1: cpu-23-1
  # cpu-23-2: cpu-23-2